compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: false
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: false
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
main_process_port: 20685
